org: '1257311667'
app: demo
stage: dev
component: layer
name: demo-layer
inputs:
  name: demo-layer
  region: ap-guangzhou
  src:
    src: ../node_modules
    targetDir: /node_modules
  runtimes:
    - Nodejs10.15
